import {supabase,restoreAuthSession,sendMagicLink,signOut} from '../../shared/js/supabase.js';
const root=document.querySelector('#adminApp');let user=null,view='dashboard',isAdmin=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function adminCheck(){if(!user)return false;const {data,error}=await supabase.from('platform_admins').select('user_id,role,status').eq('user_id',user.id).eq('status','active').maybeSingle();if(error){console.error(error);return false}return !!data}
function login(message=''){root.className='';root.innerHTML=`<main class="login-shell"><section class="login-card"><div class="brand"><img src="assets/galaxy-cue-mark-transparent.png" alt="Galaxy Cue"><div><div class="eyebrow">Platform Administration</div><h1>Galaxy Cue Admin OS</h1></div></div><p class="muted">Developer and platform operations only. Business event management belongs in Business OS.</p>${message?`<div class="notice">${esc(message)}</div>`:''}<form id="loginForm"><label>Email</label><input type="email" name="email" required autocomplete="email" placeholder="developer@galaxycue.com"><button class="btn primary">Email secure admin link</button></form><p class="muted">Access requires an active record in <code>platform_admins</code>.</p></section></main>`;document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');const {error}=await sendMagicLink(email);login(error?error.message:`Secure link sent to ${email}.`)})}
async function safeCount(table){const {count,error}=await supabase.from(table).select('*',{count:'exact',head:true});return error?'—':count??0}
async function loadData(){const [businesses,clients,events,admins]=await Promise.all([supabase.from('businesses').select('id,name,slug,created_at').order('created_at',{ascending:false}).limit(100),supabase.from('clients').select('id,business_id,name,email,created_at').order('created_at',{ascending:false}).limit(100),supabase.from('events').select('id,business_id,title,event_type,event_date,status,created_at').order('created_at',{ascending:false}).limit(100),supabase.from('platform_admins').select('user_id,role,status,created_at').order('created_at',{ascending:false})]);return {businesses:businesses.data||[],clients:clients.data||[],events:events.data||[],admins:admins.data||[],errors:[businesses.error,clients.error,events.error,admins.error].filter(Boolean)}}
function shell(content){root.className='';root.innerHTML=`<div class="admin-shell"><aside class="sidebar"><div class="brand"><img src="assets/galaxy-cue-mark-transparent.png" alt="GC"><div><strong>Galaxy Cue</strong><div class="eyebrow">Admin OS</div></div></div><nav class="nav">${[['dashboard','Dashboard'],['businesses','Businesses'],['users','Users'],['system','System'],['templates','Templates'],['developers','Developers']].map(([id,label])=>`<button data-view="${id}" class="${view===id?'active':''}">${label}</button>`).join('')}</nav><div class="sidebar-footer"><a class="btn" href="index.html">Open Business OS</a><button class="btn" id="logout" style="margin-top:8px;width:100%">Sign out</button></div></aside><main class="main">${content}</main></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelector('#logout').onclick=async()=>{await signOut();user=null;login()}}
async function render(){const data=await loadData();const counts={businesses:await safeCount('businesses'),clients:await safeCount('clients'),events:await safeCount('events'),requests:await safeCount('booking_requests')};const head=`<header class="topbar"><div><div class="eyebrow">Galaxy Cue Platform</div><h1>${view[0].toUpperCase()+view.slice(1)}</h1><p class="muted">Signed in as ${esc(user.email)}</p></div><span class="pill">v7.0.0</span></header>${data.errors.length?'<div class="notice">Some platform data could not be read. Run the v7 platform migration and verify admin permissions.</div>':''}`;
if(view==='dashboard')return shell(head+`<section class="cards"><div class="card metric"><small>Entertainment Companies</small><strong>${counts.businesses}</strong></div><div class="card metric"><small>Clients</small><strong>${counts.clients}</strong></div><div class="card metric"><small>Events</small><strong>${counts.events}</strong></div><div class="card metric"><small>Booking Requests</small><strong>${counts.requests}</strong></div></section><section class="section card"><h2>Platform boundaries</h2><p class="muted">Admin OS manages the Galaxy Cue platform. Business OS manages entertainment companies. Client App manages client-facing event collaboration.</p></section>`);
if(view==='businesses')return shell(head+table('Businesses',['Name','Booking handle','Created'],data.businesses.map(x=>[x.name,x.slug,new Date(x.created_at).toLocaleDateString()])));
if(view==='users')return shell(head+`<section class="cards"><div class="card metric"><small>Business users</small><strong>Managed by memberships</strong></div><div class="card metric"><small>Client records</small><strong>${counts.clients}</strong></div></section>`+table('Recent clients',['Client','Email','Business ID'],data.clients.map(x=>[x.name,x.email,x.business_id])));
if(view==='system')return shell(head+`<section class="cards"><div class="card"><h3>Authentication</h3><p class="muted">Supabase magic links active.</p></div><div class="card"><h3>Application surfaces</h3><p class="muted">Admin OS · Business OS · Client App</p></div><div class="card"><h3>Current release</h3><p class="muted">Architecture separation foundation.</p></div></section>`);
if(view==='developers')return shell(head+table('Platform administrators',['User ID','Role','Status'],data.admins.map(x=>[x.user_id,x.role,x.status]))+`<section class="section card"><h2>Developer links</h2><p><a href="index.html">Business OS</a> · <a href="client-portal.html">Client App</a></p></section>`);
return shell(head+`<section class="card empty"><h2>${view[0].toUpperCase()+view.slice(1)}</h2><p>This platform module now has its own clean boundary and is ready for focused development.</p></section>`)}
function table(title,heads,rows){return `<section class="section"><div class="section-head"><h2>${title}</h2><span class="pill">${rows.length}</span></div><div class="table-wrap">${rows.length?`<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty">No records found.</div>'}</div></section>`}
(async()=>{const restored=await restoreAuthSession();user=restored.user;if(!user)return login(restored.error?.message||'');isAdmin=await adminCheck();if(!isAdmin)return login('This account is signed in but is not authorized for Galaxy Cue Admin OS.');render()})();
